# Generated by Django 3.2.8 on 2021-10-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='release_year',
            field=models.IntegerField(),
        ),
    ]
